---
title: "Homework 1"
author: Ling Tuo
date: 09/19/2020
output: 
  github_document:
    toc: true
---

This is my solution to HW1. 

```{r, message = FALSE}
library(tidyverse)
```

## Problem 1

Create a dataframe with specified elements.

```{r}
prob1_df = 
  tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor(c("low", "low", "low", "mod", "mod", "mod", "mod", "high", "high", "high"))
  )
```

Take the mean of each variable in my data frame.

```{r means, collapse = TRUE}
mean(pull(prob1_df, samp))
mean(pull(prob1_df, samp_gt_0))
mean(pull(prob1_df, char_vec))
mean(pull(prob1_df, factor_vec))
```

I can take the mean of numbers and logical but not character or factor.

```{r as_numeric, collapse = TRUE}
as.numeric(pull(prob1_df, samp))
as.numeric(pull(prob1_df, samp_gt_0))
as.numeric(pull(prob1_df, char_vec))
as.numeric(pull(prob1_df, factor_vec))
```

Logical and factor variables can be converted into numeric but character cannot.

```{r convert, collapse = TRUE}
as.numeric(pull(prob1_df, samp_gt_0))*pull(prob1_df, samp)
as.factor(pull(prob1_df, samp_gt_0))*pull(prob1_df, samp)
as.numeric(as.factor(pull(prob1_df, samp_gt_0)))*pull(prob1_df, samp)
```


## Problem 2

Load penguins dataset.

```{r}
data("penguins", package = "palmerpenguins")
```

